import React, { ReactNode } from 'react';
import { Container } from '@chakra-ui/react';
import { Header } from '../Header';
import Head from 'next/head';

export const Layout = ({ children }: { children: ReactNode }) => {
  return (
    <>
      <Head>
        <title>Palace centro de imagen</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Container as='section' minH='100%' maxW='container.lg'>
        {children}
      </Container>
    </>
  );
};
