import React, { ReactNode } from 'react';
import { Container, Box } from '@chakra-ui/react';
import { Header } from '../Header';
import Head from 'next/head';
import { Navbar } from 'src/components';
import { useSession } from 'next-auth/react';

export const Layout = ({ children }: { children: ReactNode }) => {
  const { data, status, ...rest } = useSession();

  const isLoading = status === 'loading';

  if (isLoading) return <div>Loading...</div>;

  const isUnauthenticated = status === 'unauthenticated';

  const userData = data?.userData;

  const { role, fullName } = userData || {};

  return (
    <>
      <Head>
        <title>Palace centro de imagen</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {!isUnauthenticated && (
        <Header fullName={fullName} role={role} isLoading={isLoading} />
      )}

      <Container as='section' minH='100%' maxW='container.lg'>
        {children}
        {!isUnauthenticated && (
          <Box mt={8}>
            <Navbar role={role} />
          </Box>
        )}
      </Container>
    </>
  );
};
