import { Container } from '@chakra-ui/react';
import { useAuth } from 'context/AuthContext';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect } from 'react';
import { ServiceList, Resume, Navbar } from 'src/components';
import { useServices } from 'src/services/useServices';
import { useUsers } from 'src/services/useUsers';

const Home: NextPage = () => {
  const {
    getBarberServices,
    getUserServices,
    userServices,
    isLoadingServices,
  } = useAuth();

  const { user, users, getUsers } = useUsers();
  const { getServices, services } = useServices();

  useEffect(() => {
    // getBarberServices();
    // getUserServices();

    if (user?.userId) {
      getServices(user.userId);
      getUsers();
    }
  }, [getServices, getUsers, user]);

  return (
    <>
      <Head>
        <title>Palace centro de imagen</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Container as='section' minH='100%'>
        <Resume services={userServices} />
        <ServiceList
          services={services}
          isLoadingServices={isLoadingServices}
          getUserServices={getServices}
          role={user?.role}
          user={user}
          users={users}
        />
      </Container>
      <Navbar />
    </>
  );
};

export default Home;
