import {
  Container,
  Box,
  IconButton,
  Flex,
  Grid,
  GridItem,
} from '@chakra-ui/react';
import { AddIcon, StarIcon } from '@chakra-ui/icons';
import { useAuth } from 'context/AuthContext';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect } from 'react';
import {
  Header,
  AddService,
  ServiceList,
  Resume,
  Layout,
  Navbar,
} from 'src/components';

const Home: NextPage = () => {
  const { services, getBarberServices } = useAuth();

  useEffect(() => {
    getBarberServices();
  }, []);

  return (
    <>
      <Head>
        <title>Palace centro de imagen</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Container as='section' minH='100%'>
        <Resume />
        <ServiceList />
      </Container>
      <Navbar />
    </>
  );
};

export default Home;
