import { Flex, Box, Container } from '@chakra-ui/react';
import { useAuth } from 'context/AuthContext';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect } from 'react';
import { Header, AddService, ServiceList, Resume } from 'src/components';

const Home: NextPage = () => {
  const { services, getBarberServices } = useAuth();

  useEffect(() => {
    getBarberServices();
  }, []);

  return (
    <>
      <Head>
        <title>Palace centro de imagen</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <Container as='main' marginTop='90px'>
        <AddService services={services} />
        <Resume />
        <ServiceList />
      </Container>

      <footer></footer>
    </>
  );
};

export default Home;
